Repository minierparedes/frog-blossom-cms, pull requests merged in 2024-06, with the labels that each got.

#24 Change the Go Module Path
  api/server.go
  cmd/main.go
  db/sqlc/main_test.go
  db/sqlc/users_test.go
  go.mod
  internal/handler/users_handler.go
Labels: build

#27 Fix typo inside README
  README.md
Labels: documentation

#36 Refactor UpdatePageTx & UpdatePostsTx to Update Single Page and Meta Entry
  db/sqlc/dtos.go
  db/sqlc/store.go
  db/sqlc/store_test.go
Labels: refactor

#35 Refactor UpdateContentTxParams & UpdateContentTxResult Struct Definition
  db/sqlc/dtos.go
Labels: refactor

#40 Setup and Configure GitHub Actions for Dev Branch
  .github/workflows/golangci-lint.yml
  .github/workflows/test-backend.yml
  .gitignore
Labels: build

#38 Separate UpdateContentTxParams and UpdateContentTxResult into Pages and Posts DTOs
  db/sqlc/dtos.go
  db/sqlc/store.go
  db/sqlc/store_test.go
Labels: refactor

#43 Implement Handlers for users repository
  api/server.go
  internal/handler/users_handler.go
Labels: feature
